exports.cekResi = require('./cekResi')
exports.downloader = require('./downloader')
exports.meme = require('./meme')
exports.removebg = require('./remove-bg')
exports.urlShortener = require('./shortener')
exports.cat = require('./cat')
exports.waifu = require('./waifu')
